# Generated by Django 4.2.7 on 2023-11-15 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0002_rename_mentor_mentor_users_user_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.CharField(default='2', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='fields',
            field=models.CharField(default='java', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
