# Generated by Django 4.2.7 on 2023-11-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0003_mentor_experience_mentor_fields_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default1.png', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='field',
        ),
        migrations.AddField(
            model_name='mentee',
            name='fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
        ),
    ]
