# Generated by Django 4.2.7 on 2023-11-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0004_course_remove_mentee_field_mentee_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='fields',
        ),
    ]
