# Generated by Django 4.2.7 on 2023-11-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0005_remove_mentee_fields_remove_mentor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
        ),
    ]
