# Generated by Django 4.2.7 on 2023-11-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0006_mentee_fields_mentor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='mentor',
        ),
    ]
