# Generated by Django 4.2.7 on 2023-11-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0008_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0799069642', max_length=15),
            preserve_default=False,
        ),
    ]
