# Generated by Django 4.2.7 on 2023-11-16 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0015_event_fromt_event_tot_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='me testing', max_length=15000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='fromT',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='course',
            name='toT',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
