# Generated by Django 4.2.7 on 2023-11-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0017_remove_course_date_remove_course_fromt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentorclub.mentor'),
            preserve_default=False,
        ),
    ]
