# Generated by Django 4.2.7 on 2023-11-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0018_schedule_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='mentor',
        ),
    ]
