# Generated by Django 4.2.7 on 2023-11-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0020_member_remove_mentor_course_remove_mentor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
    ]
