# Generated by Django 4.2.7 on 2023-11-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0021_remove_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
        ),
    ]
