# Generated by Django 4.2.7 on 2023-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0022_alter_member_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='interest',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(default='mentor', max_length=50),
            preserve_default=False,
        ),
    ]
