# Generated by Django 4.2.7 on 2023-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0023_rename_interest_member_experience_user_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.CharField(default='mentee', max_length=50),
            preserve_default=False,
        ),
    ]
