# Generated by Django 4.2.7 on 2023-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0024_member_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.CharField(choices=[('', 'Experience Period'), ('None', 'None'), ('1-6 months', '1-6 months'), ('6-12 months', '6-12 months'), ('1-2 yrs', '1-2 yrs'), ('2-4 yrs', '2-4 yrs'), ('above 4yrs', 'above 4yrs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='interest',
            field=models.CharField(choices=[('', 'Your Interest?'), ('mentor', 'mentor'), ('mentee', 'mentee')], max_length=50),
        ),
    ]
