# Generated by Django 4.2.7 on 2023-11-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0029_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorclub.member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(choices=[('', 'Your Interest?'), ('mentor', 'mentor'), ('mentee', 'mentee')], max_length=50),
        ),
    ]
