# Generated by Django 4.2.7 on 2023-11-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0030_alter_schedule_mentor_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorclub.course'),
        ),
    ]
