# Generated by Django 4.2.7 on 2023-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0032_schedule_unique_course_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Your Gender?'), ('m', 'Male'), ('f', 'female')], default='f', max_length=30),
            preserve_default=False,
        ),
    ]
