# Generated by Django 4.2.7 on 2023-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorclub', '0033_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='i love coding', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Your Gender?'), ('male', 'Male'), ('female', 'Female')], max_length=30),
        ),
    ]
